# Generated by Django 3.1.1 on 2020-10-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppetizerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('V', 'Vegetarian'), ('O', 'One Order Per Person'), ('N', 'Noodles'), ('S', 'Soups'), ('SA', 'Salads')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BeerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Draft'), ('DM', 'Domestic'), ('IM', 'Imported')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DesertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('I', 'Ice Cream'), ('M', 'Mochi Ice Cream')], max_length=1)),
                ('limits', models.CharField(choices=[('O', 'One Per Person'), ('T', 'Two Per Person')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NigiriItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('R', 'Raw'), ('C', 'Cooked'), ('O', 'One Order Per Person'), ('V', 'Vegetarian')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Deep Fried'), ('B', 'Baked'), ('S', 'Spicy'), ('O', 'One Order Per Person'), ('V', 'Vegetarian')], max_length=1)),
                ('options', models.CharField(choices=[('H', 'Hand Rolls'), ('N', 'No Hand Rolls')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SakeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('H', 'House Sake'), ('G', 'Gin-Jo'), ('J', 'Jun-Mai'), ('D', 'Dai-Gin-Jo'), ('N', 'Nigori'), ('S', 'Sparkling'), ('F', 'Flavored'), ('SJ', 'Soju'), ('SH', 'Shooters')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SoftDrinkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('R', 'Refillable'), ('NR', 'Not Refillable')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(default='food_images/default.jpg', upload_to='food_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('W', 'White Wine'), ('R', 'Red Wine')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
