# Generated by Django 3.1.1 on 2020-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201005_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollitem',
            old_name='options',
            new_name='hand_roll_options',
        ),
        migrations.AddField(
            model_name='appetizeritem',
            name='vegetarian_options',
            field=models.CharField(blank=True, choices=[('V', 'Vegetarian')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nigiriitem',
            name='vegetarian_options',
            field=models.CharField(blank=True, choices=[('V', 'Vegetarian')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rollitem',
            name='spicy_options',
            field=models.CharField(blank=True, choices=[('S', 'Spicy')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='appetizeritem',
            name='category',
            field=models.CharField(choices=[('A', 'Appetizer'), ('N', 'Noodles'), ('S', 'Soups'), ('SA', 'Salads')], max_length=2),
        ),
        migrations.AlterField(
            model_name='nigiriitem',
            name='category',
            field=models.CharField(choices=[('R', 'Raw'), ('C', 'Cooked')], max_length=1),
        ),
        migrations.AlterField(
            model_name='rollitem',
            name='category',
            field=models.CharField(choices=[('F', 'Fresh'), ('D', 'Deep Fried'), ('B', 'Baked'), ('V', 'Vegetarian')], max_length=1),
        ),
    ]
