# Generated by Django 3.1.1 on 2020-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20201005_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollitem',
            name='hand_roll_options',
            field=models.CharField(blank=True, choices=[('H', 'Hand Rolls')], max_length=1, null=True),
        ),
    ]
