# Generated by Django 3.1.1 on 2020-10-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20201005_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollitem',
            name='vegetarian_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appetizeritem',
            name='vegetarian_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nigiriitem',
            name='vegetarian_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rollitem',
            name='hand_roll_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rollitem',
            name='spicy_options',
            field=models.BooleanField(default=False),
        ),
    ]
