# Generated by Django 3.1.1 on 2020-10-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20201005_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sakeitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sakeitem',
            name='price',
        ),
    ]
