# Generated by Django 3.1.1 on 2020-10-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20201010_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollitem',
            name='long_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rollitem',
            name='category',
            field=models.CharField(choices=[('F', 'Fresh'), ('D', 'Deep Fried'), ('B', 'Baked')], max_length=1),
        ),
    ]
